apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "airflow.fullname" . }}-env"
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    timestamp: "{{ date "20060102150405" .Release.Time }}"
data:
  ## Force UTC timezone
  TZ: Etc/UTC
  ## DB configuration (For Postgres)
  DATABASE_HOST: "{{ template "airflow.postgresql.fullname" . }}"
  DATABASE_PORT: "{{ .Values.postgresql.service.port }}"
  DATABASE_DB: "{{ .Values.postgresql.postgresDatabase }}"

  # bash command which echos the DB connection string in SQLAlchemy format
  DATABASE_SQLALCHEMY_CMD: |-
    {{ include "DATABASE_SQLALCHEMY_CMD" . }}

  FERNET_KEY: "{{ .Values.airflow.fernetKey }}"
  DO_WAIT_INITDB: "false"
  ## Custom Airflow settings
  # LocalExecutor DaskExecutor
  AIRFLOW__CORE__EXECUTOR: "DaskExecutor"
  AIRFLOW__DASK__CLUSTER_ADDRESS: {{ template  "dask.fullname" . }}-{{ .Values.dask.scheduler.name }}:{{ .Values.dask.scheduler.servicePort }}
  AIRFLOW__CORE__DONOT_PICKLE: "{{ .Values.dags.doNotPickle }}"
  AIRFLOW__CORE__DAGS_FOLDER: "{{ .Values.dags.path }}"
  AIRFLOW__CORE__BASE_LOG_FOLDER: "{{ .Values.logs.path }}"
  AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "{{ printf "%s/%s" .Values.logs.path "dag_processor_manager/dag_processor_manager.log" }}"
  AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: "{{ printf "%s/%s" .Values.logs.path "scheduler" }}"
  
  # bash command which echos the DB connection string in SQLAlchemy format
  AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD: |-
    bash -c 'eval "$DATABASE_SQLALCHEMY_CMD"'

  # configure smtp
  {{- if .Values.airflowSmtp.enabled }}
  AIRFLOW__SMTP__SMTP_HOST: "{{ .Values.airflowSmtp.smtpServerName }}"
  AIRFLOW__SMTP__SMTP_STARTTLS: "{{ .Values.airflowSmtp.startTLS }}"
  AIRFLOW__SMTP__SMTP_SSL: "{{ .Values.airflowSmtp.useSSL }}"
  AIRFLOW__SMTP__SMTP_PORT: "{{ .Values.airflowSmtp.smtpServerPort }}"
  AIRFLOW__SMTP__SMTP_MAIL_FROM: "{{ .Values.airflowSmtp.smtpMailFrom }}"
  {{- if .Values.airflowSmtp.credential.enabled }}
  AIRFLOW__SMTP__SMTP_USER: "{{ .Values.airflowSmtp.credential.user }}"
  AIRFLOW__SMTP__SMTP_PASSWORD: "{{ .Values.airflowSmtp.credential.password }}"
  {{- end }}
  {{- end }}

  # Disabling XCom pickling for forward compatibility
  AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "false"
  {{- if .Values.websiteAuthentication.enabled }}
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.google_auth"
  AIRFLOW__GOOGLE__OAUTH_CALLBACK_ROUTE: "{{ .Values.websiteAuthentication.googleOAuthCallbackRoute }}"
  AIRFLOW__GOOGLE__DOMAIN: "{{ .Values.websiteAuthentication.googleOAuthAuthenticatedDomain }}"
  AIRFLOW__GOOGLE__PROMPT: "{{ .Values.websiteAuthentication.googleOAuthPrompt }}"
  {{- end }}
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
  # Note: changing `Values.airflow.customEnvironmentVariables` won't change the configmap checksum and so won't make
  # the pods to restart

  {{- range $setting, $option := .Values.airflow.customEnvironmentVariables }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
