apiVersion: v1
kind: Service
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "airflow.name" . }}
    component: dask-worker
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    component: dask-worker
    name: {{ template "dask.fullname" . }}-dask-worker
    app: {{ template "airflow.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name }}
    chart: {{ template "airflow.chart" . }}
  ports:
    - name: {{ template "dask.fullname" . }}-dask-worker
      port: 8793
      protocol: TCP
  clusterIP: None
