apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "airflow.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "airflow.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.dask.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "airflow.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.dask.worker.image.pullSecrets | nindent 8 }}
      {{- if .Values.dags.initContainer.enabled }}
      initContainers:
        {{- range .Values.dags.git.git_urls }}
        - name: git-clone-{{ printf "%s" .name | replace "_" "-"  }}
          image: {{ $.Values.dags.initContainer.image.repository }}:{{ $.Values.dags.initContainer.image.tag }}  # Any image with git will do
          imagePullPolicy: {{ $.Values.dags.initContainer.image.pullPolicy }}
          command:
            - /usr/local/git/git-clone.sh
          args:
            - "{{ .url }}"
            - "{{ .ref }}"
            - "{{ .name }}"
            - "{{ .installPriority }}"
            - "/dags"
          volumeMounts:
            - name: git-clone
              mountPath: /usr/local/git
            - name: dags-data
              mountPath: /dags
            {{- if $.Values.dags.git.secret }}
            - name: git-clone-secret
              mountPath: /keys
            {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ template "dask.fullname" . }}-worker
          image: "{{ .Values.dask.worker.image.repository }}:{{ .Values.dask.worker.image.tag }}"
          imagePullPolicy: {{ .Values.dask.worker.image.pullPolicy }}
          volumeMounts:
            - name: scripts
              mountPath: /usr/local/scripts
          {{- if .Values.persistence.enabled }}
            - name: dags-data
              mountPath: {{ .Values.dags.path }}
              subPath: {{ .Values.persistence.subPath | default "" }}
          {{- else if .Values.dags.initContainer.enabled }}
            - name: dags-data
              mountPath: {{ .Values.dags.path }}
          {{- end }}
          ports:
            - containerPort: 8789
          resources:
            {{- toYaml .Values.dask.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.dask.worker.env | nindent 12 }}
          args:
            - "bash"
            - "-c"
            - >
              {{- if and ( .Values.dags.initContainer.enabled ) ( .Values.dags.initContainer.installRequirements ) }}
                apt update -y &&
                apt install build-essential -y &&
                pip install --upgrade pip &&
                /usr/local/scripts/install-requirements.sh &&
              {{- end }}
                {{ .Values.dask.worker.image.dask_worker }}  {{ template "dask.fullname" . }}-scheduler:{{ .Values.dask.scheduler.servicePort }} --no-bokeh
                {{- if .Values.dask.worker.resources.limits }}
                  {{ .Values.dask.worker.resources.limits.cpu | default .Values.dask.worker.default_resources.cpu | quote }} --memory-limit {{ .Values.dask.worker.resources.limits.memory | default .Values.dask.worker.default_resources.memory | quote }}
                {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ template "airflow.fullname" . }}-scripts
            defaultMode: 0755
        {{- range .Values.web.secrets }}
        - name: {{ . }}-volume
          secret:
            secretName: {{ . }}
        {{- end }}
        - name: dags-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim | default (include "airflow.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.logsPersistence.enabled }}
        - name: logs-data
          persistentVolumeClaim:
            claimName: {{ .Values.logsPersistence.existingClaim | default (printf "%s-logs" (include "airflow.fullname" . | trunc 58 )) }}
        {{- end }}
        {{- if .Values.dags.initContainer.enabled }}
        - name: git-clone
          configMap:
            name: {{ template "airflow.fullname" . }}-git-clone
            defaultMode: 0755
        {{- if .Values.dags.git.secret }}
        - name: git-clone-secret
          secret:
            secretName: {{ .Values.dags.git.secret }}
            defaultMode: 0700
        {{- end }}
        {{- end }}
