{{ if .Values.dask.jupyter.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dask.fullname" . }}-jupyter-config
  labels:
    app: {{ template "airflow.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "airflow.chart" . }}
    component: jupyter
data:
  #TODO : put behind authorization
  jupyter_notebook_config.py: |
    from oauthenticator.google import GoogleOAuthenticator
    c = get_config()
    c.JupyterHub.authenticator_class = GoogleOAuthenticator
    c.GoogleOAuthenticator.hosted_domain = ['{{ .Values.websiteAuthentication.googleOAuthAuthenticatedDomain }}']
    c.NotebookApp.password = '{{ .Values.dask.jupyter.password }}'


{{ end }}
