apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}
    component: web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.airflow.service.websitePrefix }}.elifesciences.org
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.clientCertificate }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: {{ .Values.airflow.service.type }}
  selector:
    app: {{ template "airflow.name" . }}
    component: web
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.airflow.service.externalPort | default 443 }}
      targetPort: 8080
